### ISSUE TITLE
🐛 Android: build fails with: 2 files found with path 'lib/x86_64/libreactnativejni.so'

### ISSUE THREAD

**Issue by rodgomesc** [margelo/react-native-vision-camera#365]
### What were you trying to do?

i'm trying to build the app for a android emulator device, but the build always fails with the error above, I figured out how to solve this, but I believe it's not the best approach. is anyone else going through this? I'm leaving it registered here if someone experiences the same problem.

 ###  workaround
  
 * open `android/app/build.gradle`

 ```js 
 
 android {
    packagingOptions {   \\ <- add this
        pickFirst '**/*.so'
    }
    
  ```

### What happened instead?

Build fails with: 2 files found with path 'lib/x86_64/libreactnativejni.so'

### Relevant log output

```shell
example git:(master) ✗ yarn android
yarn run v1.22.11
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 937 file(s) to forward-jetify. Using 12 workers...
info Starting JS server...
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :react-native-vision-camera
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
WARNING:: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
WARNING:: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
WARNING:: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
WARNING:: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
WARNING:: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
WARNING:: The specified Android SDK Build Tools version (30.0.0) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.1.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '30.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: root project 'VisionCameraFaceDetectorExample', project ':app', project ':react-native-reanimated', ...

> Task :react-native-vision-camera:compileDebugKotlin
w: /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraView.kt: (265, 5): This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API.
w: /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt: (69, 5): This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API.
w: /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt: (79, 5): This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API.
w: /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt: (90, 5): This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API.
w: /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt: (115, 5): This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API.
w: /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt: (129, 5): This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API.

> Task :app:compileDebugJavaWithJavac

> Task :react-native-vision-camera:generateJsonModelDebug
/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt:122 (message):
  VisionCamera linking: FOR_HERMES=false

/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt:122 (message):
  VisionCamera linking: FOR_HERMES=false

/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Warning at /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt:122 (message):
  VisionCamera linking: FOR_HERMES=false

/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Warning at /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt:122 (message):
  VisionCamera linking: FOR_HERMES=false

/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|x86 : CMake Warning at /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt:122 (message):
  VisionCamera linking: FOR_HERMES=false

/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|x86 : CMake Warning at /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt:122 (message):
  VisionCamera linking: FOR_HERMES=false

/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|x86_64 : CMake Warning at /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt:122 (message):
  VisionCamera linking: FOR_HERMES=false

/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|x86_64 : CMake Warning at /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/CMakeLists.txt:122 (message):
  VisionCamera linking: FOR_HERMES=false


> Task :react-native-vision-camera:downloadBoost
Download https://github.com/react-native-community/boost-for-react-native/releases/download/v1.63.0-0/boost_1_63_0.tar.gz

> Task :react-native-vision-camera:downloadDoubleConversion
Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz

> Task :react-native-vision-camera:downloadFolly
Download https://github.com/facebook/folly/archive/v2020.01.13.00.tar.gz

> Task :react-native-vision-camera:downloadGlog
Download https://github.com/google/glog/archive/v0.3.5.tar.gz

> Task :react-native-vision-camera:externalNativeBuildDebug
Build VisionCamera_armeabi-v7a
ninja: Entering directory `/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/.cxx/cmake/debug/armeabi-v7a'
Build VisionCamera_arm64-v8a
ninja: Entering directory `/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/.cxx/cmake/debug/arm64-v8a'
Build VisionCamera_x86
ninja: Entering directory `/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/.cxx/cmake/debug/x86'
Build VisionCamera_x86_64
ninja: Entering directory `/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/.cxx/cmake/debug/x86_64'

> Task :app:mergeDebugNativeLibs FAILED
79 actionable tasks: 79 executed
Note: /home/rodgomesc/workspace/vision-camera-face-detector/example/android/app/src/debug/java/com/example/visioncamerafacedetector/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'lib/x86_64/libreactnativejni.so' from inputs:
      - /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/build/intermediates/library_jni/debug/jni
      - /home/rodgomesc/.gradle/caches/transforms-2/files-2.1/d1ec93b89ff5037f3f5e4741733617ec/jetified-react-native-0.64.2/jni
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 17s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: /home/rodgomesc/workspace/vision-camera-face-detector/example/android/app/src/debug/java/com/example/visioncamerafacedetector/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'lib/x86_64/libreactnativejni.so' from inputs:
      - /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/react-native-vision-camera/android/build/intermediates/library_jni/debug/jni
      - /home/rodgomesc/.gradle/caches/transforms-2/files-2.1/d1ec93b89ff5037f3f5e4741733617ec/jetified-react-native-0.64.2/jni
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 17s

    at makeError (/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/execa/index.js:174:9)
    at /home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/home/rodgomesc/workspace/vision-camera-face-detector/example/node_modules/@react-native-community/cli/build/index.js:186:9)
```

### Device

Android Emulator (Android 12)

### VisionCamera Version

^2.5.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by joshua-smith4** [comment]
A very similar problem is cropping up when trying to build Android app with hermes enabled. I created a small pull request #741 that fixes the issue that adds "**/libhermes.so" to the packagingOptions -> excludes field.
